config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("nojco_disc_golf.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path('scorecard/', include('nojco_disc_golf.scorecard.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

nojco_disc_golf/scorecard/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'scorecard'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('round/<int:pk>/', views.RoundView.as_view(), name='round'),
    path('hole/<int:pk>/', views.HoleView.as_view(), name='hole'),
    path('new_round', views.new_round, name='new_round'),
    path('add_player_to_round/<int:roundid>/<int:playerid>', views.add_player_to_round, name='add_player_to_round'),
    path('add_new_player_to_round/<int:roundid>', views.add_new_player_to_round, name='add_new_player_to_round'),
    path('previous_rounds', views.PreviousRounds.as_view(), name='previous_rounds'),
    path('complete_round/<int:roundid>', views.complete_round, name='complete_round'),
    path('delete_round/<int:roundid>', views.delete_round, name='delete_round'),
    path('current_round', views.current_round, name='current_round'),
    path('calculate_handicaps', views.calculate_handicaps, name='calculate_handicaps'),
    path('player_handicaps', views.PlayerHandicaps.as_view(), name='player_handicaps'),
    path('next_hole/<int:pk>', views.next_hole, name='next_hole'),
    path('previous_hole/<int:pk>', views.previous_hole, name='previous_hole'),


    # JSON
    
    path('save_scores/<int:roundid>', views.save_scores, name='save_scores'),
    path('update_scores/<int:roundid>', views.update_scores, name='update_scores'),
    path('update_scores_for_hole/<int:holeid>', views.update_scores_for_hole, name='update_scores_for_hole'),
    path('get_score_json/<int:roundid>', views.get_score_json, name='get_score_json'),

    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nojco_disc_golf/users/urls.py
from django.urls import path

from nojco_disc_golf.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

nojco_disc_golf/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for NOJCO Disc Golf."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

nojco_disc_golf/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

nojco_disc_golf/scorecard/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.http import JsonResponse
from django.core import serializers
import pprint

from .models import Round, Player, Hole, Course, Score, RoundPlayers


class IndexView(generic.ListView):
    model = Course
    template_name = 'scorecard/index.html'

    
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['courses'] = Course.objects.all()
        context['rounds'] = Round.objects.filter(active=True)
        return context

class PreviousRounds(generic.ListView):
    model = Round
    template_name = 'scorecard/previous_rounds.html'
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['courses'] = Course.objects.all()
        context['rounds'] = Round.objects.filter(active=False).order_by('-date')
        return context
    


class RoundView(generic.DetailView):
    model = Round
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['players'] = Player.objects.all()
        context['score_options'] = range(8)
        context['autosave'] = True
        context['all_scores'] = Score.objects.filter(round=self.object)
        holes = self.object.hole_set.all()
        # print (holes)

        return context

class HoleView(generic.DetailView):
    model = Hole

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['players'] = Player.objects.all()
        context['score_options'] = range(10)
        context['autosave'] = True

        hole = context['hole']

        if hole.hole_num > 1:
            context['prev_hole'] = hole.pk -1
        
        if hole.hole_num < hole.round.hole_set.count():
            context['next_hole'] = hole.pk +1
        
        return context


# class ResultsView(generic.DetailView):
#     model = Question
#     template_name = 'polls/results.html'

# /scorecard/new_round?course=<id>
def new_round(request):
    # Get the requested course
    try:
        course = Course.objects.get(pk=request.POST['course'])
    except (KeyError, Course.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'scorecard/error.html', {
            'course': request.POST['course'],
            'error_message': "You didn't select a valid course.",
        })
    else:
        # Set the title based on the posted info or pull from the course
        try:
            if (not request.POST['title']):
                rt = course.name
            else:
                rt=request.POST['title']
        except:
            rt = course.name
        
        # Create a round from the course
        rnd = course.round_set.create( title = rt, date = timezone.now())

        # Create holes for the round
        if (course.holes > course.coursehole_set.count()):

            for i in range(course.holes) :
                rnd.hole_set.create(hole_num = i+1)
        else:
            for ch in course.coursehole_set.all():
                rnd.hole_set.create(hole_num = ch.hole_num, par = ch.par, distance = ch.distance)
                
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        # Send user to the round view to add players/track scores
        return HttpResponseRedirect(reverse('scorecard:round', args=(rnd.id,)))

# /scorecard/add_player_to_round/<round>
def add_player_to_round(request, roundid, playerid):
    # Get the requested course
    try:
        rnd = Round.objects.get(pk=roundid)
    except (KeyError, Round.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'scorecard/error.html', {
            'round': roundid,
            'error_message': "You didn't select a valid round.",
        })
    # Get the requested Player
    try:
        player = Player.objects.get(pk=playerid)
    except (KeyError, Player.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'scorecard/error.html', {
            'round': roundid,
            'player': playerid,
            'error_message': "You didn't select a valid player.",
        })

    rnd.roundplayers_set.get_or_create(player=player, handicap=round(player.handicap * (rnd.hole_set.count() / 18)))
    
    # Create holes for the round
    # TBD: Should allow tempalte holes tied to course to set par
    for hole in rnd.hole_set.all() :
        player.score_set.get_or_create(hole=hole, round=rnd)
    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    # Send user to the round view to add players/track scores
    return HttpResponseRedirect(reverse('scorecard:round', args=(rnd.id,)))

# /scorecard/save_scores/<round>
def save_scores(request, roundid):
    # Get the requested round
    try:
        round = Round.objects.get(pk=roundid)
    except (KeyError, Round.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'scorecard/error.html', {
            'round': roundid,
            'error_message': "You didn't select a valid round.",
        })
    #print (request.POST)
   # print (request.GET)
    for key, value in request.POST.items() :
        scoreid = key.split("-", 1)[1]
        score = Score.objects.get(pk=scoreid)
        score.score = value
        score.save()


    response = {
        'success' : True
    }

    # Always return an HttpResponseRedirect after successfully dealing
    # with POST data. This prevents data from being posted twice if a
    # user hits the Back button.
    # Send user to the round view to add players/track scores
    return JsonResponse(response)

# /scorecard/complete_round/<round>
def complete_round(request, roundid):
    # Get the requested round
    try:
        round = Round.objects.get(pk=roundid)
    except (KeyError, Round.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'scorecard/error.html', {
            'round': roundid,
            'error_message': "You didn't select a valid round.",
        })
    round.active=False
    round.save()
    return HttpResponseRedirect(reverse('scorecard:index'))

# /scorecard/delete_round/<round>
def delete_round(request, roundid):
    # Get the requested round
    try:
        round = Round.objects.get(pk=roundid)
    except (KeyError, Round.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'scorecard/error.html', {
            'round': roundid,
            'error_message': "You didn't select a valid round.",
        })
    round.delete()
    return HttpResponseRedirect(reverse('scorecard:index'))

# /scorecard/current_round
def current_round(request):
    # Get the requested round
    try:
        round = Round.objects.filter(active=True).latest('date')
    except (KeyError, Round.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'scorecard/error.html', {
            'error_message': "No current round found.",
        })

    return HttpResponseRedirect(reverse('scorecard:round', args=(round.id,)))

class PlayerHandicaps(generic.ListView):
    model = Player
    template_name = 'scorecard/player_handicaps.html'
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context['players'] = Player.objects.all().order_by('handicap')
        context['rounds'] = Round.objects.all()
        return context

# /scorecard/delete_round/<round>
def calculate_handicaps(request):
    # Loop over all players
    for player in Player.objects.all():
        # Get last 3 complete rounds
        roundplayers = player.roundplayers_set.order_by("-round__date")[:5]
        # for each round
        round_total = 0
        rounds = 0
        best_round = {
            'delta' : 100
        } 
        for roundplayer in roundplayers:
            # for each score
            total = 0
            holes = 0
            for score in Score.objects.filter(round = roundplayer.round, player = player):
                # total score (raw) 
                # TODO: add per hole par
                total += score.score
                holes += 1
            if holes == 0:
                continue
            # Subtract par for course to get relative difference
            delta1 = total - roundplayer.round.course.par
            delta = delta1 /  (holes / 18)
            #print ("%s - %s - %s - %s - %s" % (player.name, roundplayer.round.title, delta1, delta , holes))
            # Combine total-par
            round_total += delta
            rounds += 1
            if delta1 < best_round['delta']:
                best_round['delta'] = delta1
                best_round['round'] = roundplayer.round.pk
        # Average over 3 rounds, with a factor
        #print (rounds)
        if rounds > 0:
            hdcp = (round_total/rounds) * .75
            # If changed, create historical
            if (True or round(hdcp) != player.handicap):
                
                #print ("%s - %s -> %s" % (player.name, player.handicap , hdcp))

nojco_disc_golf/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

nojco_disc_golf/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="content-language" content="en" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>NOJCO Disc Golf - {% block title %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Disc Golf Score & Handicap Tracking by NOJCO">
    <meta name="author" content="Jonathan Hall">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
        

    <!-- Your stuff: Third-party CSS libraries go here -->
    
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'scorecard/css/scorecard.css' %}">
    
    
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>-->
 <!-- Jquery-->
 <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

 <!-- JavaScript Bundle with Popper -->
 <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script defer src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">NOJCO Disc Golf</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="{% url 'scorecard:index' %}" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false">Score Card</a>
              <div class="dropdown-menu" aria-labelledby="dropdown01">
                <a class="dropdown-item" href="{% url 'scorecard:index' %}">New Round</a>
                <a class="dropdown-item" href="{% url 'scorecard:current_round' %}">Current Round</a>
                <a class="dropdown-item" href="{% url 'scorecard:previous_rounds' %}">Previous Rounds</a>
                <a class="dropdown-item" href="{% url 'scorecard:player_handicaps' %}">View Handicaps</a>
              </div>
            </li>


            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>

      </nav>
      

    </div>

    <div class="{% block container_override %}container{% endblock %}">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {# Script tags with only code, no src (defer by default) #}
    {% endblock inline_javascript %}
    
  </body>
</html>
 