config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("nojco_disc_golf.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path('scorecard/', include('nojco_disc_golf.scorecard.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

nojco_disc_golf/scorecard/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'scorecard'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('round/<int:pk>/', views.RoundView.as_view(), name='round'),
    path('hole/<int:pk>/', views.HoleView.as_view(), name='hole'),
    path('new_round', views.new_round, name='new_round'),
    path('add_player_to_round/<int:roundid>/<int:playerid>', views.add_player_to_round, name='add_player_to_round'),
    path('add_new_player_to_round/<int:roundid>', views.add_new_player_to_round, name='add_new_player_to_round'),
    path('previous_rounds', views.PreviousRounds.as_view(), name='previous_rounds'),
    path('complete_round/<int:roundid>', views.complete_round, name='complete_round'),
    path('delete_round/<int:roundid>', views.delete_round, name='delete_round'),
    path('current_round', views.current_round, name='current_round'),
    path('calculate_handicaps', views.calculate_handicaps, name='calculate_handicaps'),
    path('player_handicaps', views.PlayerHandicaps.as_view(), name='player_handicaps'),
    path('next_hole/<int:pk>', views.next_hole, name='next_hole'),
    path('previous_hole/<int:pk>', views.previous_hole, name='previous_hole'),


    # JSON
    
    path('save_scores/<int:roundid>', views.save_scores, name='save_scores'),
    path('update_scores/<int:roundid>', views.update_scores, name='update_scores'),
    path('update_scores_for_hole/<int:holeid>', views.update_scores_for_hole, name='update_scores_for_hole'),
    path('get_score_json/<int:roundid>', views.get_score_json, name='get_score_json'),

    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nojco_disc_golf/scorecard/models.py
import datetime
from django.db import models
from django.utils import timezone
from address.models import AddressField
from nojco_disc_golf.users.models import User
from django.db.models import signals

# Create your models here.
    
class Player(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(null=True)
    handicap = models.IntegerField(default=36)
    handicap_date = models.DateTimeField('date', auto_now_add=True)
    best_round_id = models.IntegerField(null=True)
    best_delta = models.IntegerField(null=True)
    rounds_counted = models.IntegerField(null=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return self.name
    
    class Meta:
            ordering = ['name']

class Course(models.Model):
    name = models.CharField(max_length=200)
    location = AddressField(null=True)
    par = models.IntegerField(default=56)
    slope = models.IntegerField(default=0)
    holes = models.IntegerField(default=18)
    def __str__(self):
        return self.name

    class Meta:
            ordering = ['name']

class Round(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200)
    date = models.DateTimeField('date')
    par = models.IntegerField(default=56)
    active = models.BooleanField(default=True)
    def __str__(self):
        return self.title
    def fancy_title(self):
        fancy_title = self.course.name
        if (self.title != fancy_title):
            fancy_title = self.title + " (" + fancy_title + ")"
        fancy_title = fancy_title + " - " + self.date.strftime("%m/%d/%Y")
        return fancy_title
    class Meta:
            ordering = ['-date']
    
class Hole(models.Model):
    round = models.ForeignKey(Round, on_delete=models.CASCADE)
    hole_num = models.IntegerField(default=0)
    par = models.IntegerField(default=3)
    distance = models.IntegerField(null=True, blank=True)
    def __str__(self):
        return str(self.hole_num)
    
    class Meta:
            ordering = ['hole_num']
    
class CourseHole(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    hole_num = models.IntegerField(default=0)
    par = models.IntegerField(default=3)
    distance = models.IntegerField(null=True, blank=True)
    
    class Meta:
            ordering = ['hole_num']
    
class Score(models.Model):
    hole = models.ForeignKey(Hole, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    round = models.ForeignKey(Round, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    class Meta:
            ordering = ['hole__hole_num', 'player__name']

class RoundPlayers(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    round = models.ForeignKey(Round, on_delete=models.CASCADE)
    handicap = models.IntegerField(default=36)
    class Meta:
            ordering = ['player__name']

class HistoricalHandicaps(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    handicap = models.IntegerField(default=36)
    handicap_date = models.DateTimeField('date')

class UserFriends(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)



def user_post_save(sender, instance, created, *args, **kwargs):
    """Argument explanation:

       sender - The model class. (User)
       instance - The actual instance being saved.
       created - Boolean; True if a new record was created.

       *args, **kwargs - Capture the unneeded `raw` and `using`(1.3) arguments.
    """
    if created:
        try:
            players = Player.objects.filter(name__icontains=instance.username)
            player = players.first()
        except (KeyError, Player.DoesNotExist):
            player = instance.player_set.create(name=instance.username)
    elif instance.username == 'admin':
        return
    else:
        
        try:
            player = Player.objects.get(user=instance)
            player.name = instance.name
            player.save()
        except:
            try:
                players = Player.objects.filter(name__icontains=instance.username)
                player = players.first()
                player.user = instance
                player.save()
            except (KeyError, Player.DoesNotExist):
                player = Player.objects.create(name=instance.username)

signals.post_save.connect(user_post_save, sender=User)
    

nojco_disc_golf/scorecard/templates/scorecard/error.html
{% extends 'base.html' %}

    {% block title %}ERROR!{% endblock %}

    {% block content %}
<h1>{{error_message}}</h1>


{% endblock %}

nojco_disc_golf/scorecard/templates/scorecard/hole_detail.html
{% extends 'base.html' %}

    {% block title %}Round {{ obect.title }}{% endblock %}
    
    {% block container_override %}container_details {% endblock %}

    {% block content %}
            {% if object %}
                    <div class="fixed-top thead border-bottom">
                        <h1>{{ hole.round.fancy_title }} Score Card</h1>
                        <h2>Hole {{ hole.hole_num }}</h2>
                        <h3>Par {{ hole.par }}</h3>
                        {% if hole.distance > 1 %}
                        <h3>Distance {{hole.distance}}</h3>
                        {% endif %}
                                
                                
                                {% for score in hole.score_set.all%}
                                <div class="row">
                                    <div class="col">
                                        {{ score.player.name }}
                                    </div>
                                    <div class="col">
                                        <!--<input type="number" min="0" max="8" value="{{score.score}}" onClick="this.select();"  />-->
                                        <select name="score-{{score.id}}" class="scoreInput form-select form-select-sm score" id="{{score.id}}" {% if hole.round.active == False %}disabled="true" {% endif %}>
                                            {% for opt in score_options %}
                                                <option value="{{opt}}" {% if score.score == opt %}selected{%endif %} {% if hole.par == opt%}class="bg-info"{% elif hole.par|add:"-1" == opt%}class="bg-success"{% elif hole.par|add:"1" == opt%}class="bg-warning"{% elif hole.par|add:"2" == opt%}class="bg-danger"{% endif %}>{{opt}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                {% endfor %}
                            

                        <div class="row round_controls">
                    {% if hole.round.active %}
                    <!--
                    <div class="dropdown col">
                        <button class="btn btn-primary btn-lg dropdown-toggle" type="button" id="addPlayer" data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="d-none d-md-inline">Add Player</span>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
                                <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"></path>
                            </svg>
                            
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="addPlayer">
                            {% for plyr in players %}
                                <li><a class="dropdown-item" href="{% url 'scorecard:add_player_to_round' hole.round.id plyr.id %}">{{ plyr.name }}</a></li>
                            {% endfor %}
                                <li><div class="dropdown-item">
                                    <form action="{% url 'scorecard:add_new_player_to_round' hole.round.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="text" class="form_control" name="name" />
                                        <button class="btn btn-primary" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
                                            <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                            <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"></path>
                                        </svg></button>
                                    </form>
                                </div></li>
                        </ul>
                    </div>
                    -->
                    {% if autosave == False %}

                    <div class="col float-start">
                    <button class="btn btn-success btn-lg" id="save" >
                        Save Hole
                    </button>
                    </div>
                    {% endif %}

                    
                    <!--
                    <div class="col">
                        <button class="btn btn-success btn-lg" id="update" >
                            Update Round
                        </button>
                        </div>
                    -->
                    {% endif %}
                    <div class="col text-start">
                        {% if prev_hole %}
                    <a href="{% url 'scorecard:hole' prev_hole %}" class="btn btn-primary btn-lg"  >
                        <span><div class="d-none d-sm">Previous Hole</div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left-square" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M15 2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2zM0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm11.5 5.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
                          </svg></span>
                    </a>
                        {%endif%}
                    </div>
                    <div class="col text-center">
                    <a href="{% url 'scorecard:round' hole.round.id %}" class="btn btn-info btn-lg"  >
                        <span><div class="d-none d-sm">Scorecard</div> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-card-list" viewBox="0 0 16 16">
                            <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
                            <path d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm-1-5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zM4 8a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm0 2.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
                          </svg></span>
                    </a>
                    </div>
                    <div class="col text-end">
                        {% if next_hole %}
                    <a href="{% url 'scorecard:hole' next_hole %}" class="btn btn-success btn-lg"  >
                        <span><div class="d-none d-sm">Next Hole</div>
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-square" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M15 2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2zM0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm4.5 5.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
                          </svg>
                          </span>
                    </a>
                    {%endif%}
                    </div>
                    
                </div>
                    </div>
            {% else %}
                <p>Round does not exist.</p>
            {% endif %}  
            
        {% endblock%}

        {% block inline_javascript %}
        <script>
            function save(){
                var payload = {
                    {% for score in hole.score_set.all%}
                        'score-{{score.id}}' :  parseInt($("#{{score.id}}").val()),
                    {% endfor %}
                };
                $.ajax({
                    url : "{% url 'scorecard:save_scores' hole.round.id %}", 
                    method : "POST",
                    headers: {'X-CSRFToken': '{{csrf_token }}'},
                    data: payload,
                    dataType: "json"
                }).done(function (response) {
                    console.log(response.id + " " + response.name);
                }).fail(function (error) {
                    console.log(error);
                });
                
            }

            

            function update(){

                $.ajax({
                    url : "{% url 'scorecard:update_scores_for_hole' hole.id %}", 
                    method : "POST",
                    headers: {'X-CSRFToken': '{{csrf_token }}'},
                    dataType: "json"
                }).done(function (response) {
                    scores = JSON.parse(response.scores);
                    $.each(scores, function(idx, score){
                        $("#"+score.pk).val(score.fields.score);
                    });

                }).fail(function (error) {
                    console.log(error);
                });
                
            }

            $(document).ready(function(){
	
                $(".scoreInput").on('change', function () {
                    {% if autosave %}
                    save();
                    {% endif %}
                });
                $('#confirm-delete').on('show.bs.modal', function(e) {
                    $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
                });

                {% if autosave == False %}
                $("#save").click(function () {
                    save();
                });
                {% endif %}

                $("#update").click(function () {
                    update();
                });

                setInterval(function(){update()}, 10000);
                    
            });

        </script>
        {% endblock %}

nojco_disc_golf/scorecard/templates/scorecard/round_detail.html
{% extends 'base.html' %}

    {% block title %}Round {{ obect.title }}{% endblock %}
    
    {% block container_override %}container_details {% endblock %}

    {% block content %}
            {% if object %}
                    <div class="fixed-top thead border-bottom">
                        <h1>{{ object.fancy_title }}</h1>
                        <div class="row">
                            <div class="col" class="text-left">Hole</div>
                        {% for roundplayers in object.roundplayers_set.all %}
                            <div class="col" class="text-left">{{ roundplayers.player.name }}</div>
                        {% endfor %}
                        </div>
                    </div>
                    <div class="tbody">
                        {% for hole in object.hole_set.all %}
                            <div class="row">
                                <div class="col border-endbold"><a href="{% url 'scorecard:hole' hole.pk %}" class="btn btn-sm btn-secondary" style="width:100%">{{hole.hole_num}} ({{hole.par}})</a>
                                    </div>
                                
                                
                                {% for score in hole.score_set.all%}
                                    <div class="col">
                                        <!--<input type="number" min="0" max="8" value="{{score.score}}" onClick="this.select();"  />-->
                                        <select name="score-{{score.id}}" class="scoreInput form-select form-select-sm score" id="{{score.id}}" {% if object.active == False %}disabled="true" {% endif %}>
                                            {% for opt in score_options %}
                                                <option value="{{opt}}" {% if score.score == opt %}selected{%endif %} {% if hole.par == opt%}class="bg-info"{% elif hole.par|add:"-1" == opt%}class="bg-success"{% elif hole.par|add:"1" == opt%}class="bg-warning"{% elif hole.par|add:"2" == opt%}class="bg-danger"{% endif %}>{{opt}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                {% endfor %}
                            </div>
                            {% if hole.hole_num == 9 %}
                            <div class="row  bold bg-primary">
                                <div class="col border-end">OUT</div>
                                {% for score in hole.score_set.all%}
                                    <div class="col" id="{{ score.player.id }}-out"></div>
                                {% endfor %}
                                </div>
                            {% elif hole.hole_num == 18 %}
                            <div class="row bold bg-success">
                                <div class="col bold  border-end">IN</div>
                                {% for score in hole.score_set.all%}
                                    <div class="col" id="{{ score.player.id }}-in"></div>
                                {% endfor %}
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="fixed-bottom tfoot border-top bold">
                        <div class="row bg-secondary">
                            <div class="col border-end">SUM</div>
                            {% for roundplayers in object.roundplayers_set.all %}
                                <div class="col" id="{{ roundplayers.player.id }}-sum"></div>
                            {% endfor %}
                        </div>
                        <div class="row bg-warning">
                            <div class="col border-end">HDCP</div>
                            {% for roundplayers in object.roundplayers_set.all %}
                                <div class="col" id="{{ roundplayers.player.id }}-handicap">{{ roundplayers.handicap }}</div>
                            {% endfor %}
                        </div>
                        <div class="row bg-info">
                            <div class="col border-end">TOTAL</div>
                            {% for roundplayers in object.roundplayers_set.all %}
                                <div class="col" id="{{ roundplayers.player.id }}-total"></div>
                            {% endfor %}
                        </div>

                        <div class="row round_controls">
                    {% if object.active %}
                    <div class="dropdown col">
                        <button class="btn btn-primary btn-lg dropdown-toggle" type="button" id="addPlayer" data-bs-toggle="dropdown" aria-expanded="false">
                            <span class="d-none d-md-inline">Add Player</span>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
                                <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"></path>
                            </svg>
                            
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="addPlayer">
                            {% for plyr in players %}
                                <li><a class="dropdown-item" href="{% url 'scorecard:add_player_to_round' object.id plyr.id %}">{{ plyr.name }}</a></li>
                            {% endfor %}
                                <li><div class="dropdown-item">
                                    <form action="{% url 'scorecard:add_new_player_to_round' object.id %}" method="post">
                                        {% csrf_token %}
                                        <input type="text" class="form_control" name="name" />
                                        <button class="btn btn-primary" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
                                            <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                            <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"></path>
                                        </svg></button>
                                    </form>
                                </div></li>
                        </ul>
                    </div>
                    
                    {% if autosave == False %}

                    <div class="col">
                    <button class="btn btn-success btn-lg" id="save" >
                        Save Round
                    </button>
                    </div>
                    {% endif %}

                    
                    <!--
                    <div class="col">
                        <button class="btn btn-success btn-lg" id="update" >
                            Update Round
                        </button>
                        </div>
                    -->
                    <div class="col">
                    <a href="{% url 'scorecard:complete_round' object.id %}" class="btn btn-success btn-lg float-end"  >
                        Complete
                    </a>
                    </div>
                    <!-- TODO: add confirmation 
                    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                Confirm Round Completion
                            </div>
                            <div class="modal-body">
                                Are you sure the round is done?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                <a class="btn btn-danger btn-ok">Delete</a>
                            </div>
                        </div>
                    </div>
                    </div>
                    -->
                    {% else %}
                    <div class="col">
                        <a href="{% url 'scorecard:delete_round' object.id %}" class="btn btn-danger btn-lg float-end"  >
                            Delete Round
                        </a>
                        </div>
                    {% endif %}
                    
                </div>
                    </div>
            {% else %}
                <p>Round does not exist.</p>
            {% endif %}  
            
        {% endblock%}

        {% block inline_javascript %}
        <script>
            function score(){

                $.ajax({
                    url : "{% url 'scorecard:get_score_json' round.id %}", 
                    method : "POST",
                    headers: {'X-CSRFToken': '{{csrf_token }}'},
                    dataType: "json"
                }).done(function (response) {
                    score_data = response.score_data;
                    $.each(score_data, function(idx, player){
                        $("#"+player.player_id+"-out").html(player.out);
                        $("#"+player.player_id+"-in").html(player.in);
                        $("#"+player.player_id+"-sum").html(player.ssum);
                        $("#"+player.player_id+"-total").html(player.total);
                    });

                }).fail(function (error) {
                    console.log(error);
                });
                
            }

            function save(){
                var payload = {
                    {% for score in all_scores %}
                        'score-{{score.id}}' :  parseInt($("#{{score.id}}").val()),
                    {% endfor %}
                };
                $.ajax({
                    url : "{% url 'scorecard:save_scores' round.id %}", 
                    method : "POST",
                    headers: {'X-CSRFToken': '{{csrf_token }}'},
                    data: payload,
                    dataType: "json"
                }).done(function (response) {
                    console.log(response.id + " " + response.name);
                }).fail(function (error) {
                    console.log(error);
                });
                
            }

            

            function update(){

                $.ajax({
                    url : "{% url 'scorecard:update_scores' round.id %}", 
                    method : "POST",
                    headers: {'X-CSRFToken': '{{csrf_token }}'},
                    dataType: "json"
                }).done(function (response) {
                    scores = JSON.parse(response.scores);
                    $.each(scores, function(idx, score){
                        $("#"+score.pk).val(score.fields.score);
                    });

                }).fail(function (error) {
                    console.log(error);
                });
                
            }

            $(document).ready(function(){
                score();
	
                $(".scoreInput").on('change', function () {
                    {% if autosave %}
                    save();
                    {% endif %}
                    score();
                });
                $('#confirm-delete').on('show.bs.modal', function(e) {
                    $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
                });

                {% if autosave == False %}
                $("#save").click(function () {
                    save();
                });
                {% endif %}

                $("#update").click(function () {
                    update();
                });

                setInterval(function(){update(); score()}, 10000);
                    
            });

        </script>
        {% endblock %}